/*
 * This file is generated by jOOQ.
 */
package com.ivan.sunnyblog.base.models.tables.pojos;


import java.io.Serializable;
import java.util.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Article implements Serializable {

    private static final long serialVersionUID = -1075354833;

    private Long    articleId;
    private Short   status;
    private String  title;
    private String  content;
    private String  firstPicture;
    private Integer viewCount;
    private Long    userId;
    private Long    categoryId;
    private Date    createDate;
    private Date    updateDate;
    private String  description;
    private Short   type;

    public Article() {}

    public Article(Article value) {
        this.articleId = value.articleId;
        this.status = value.status;
        this.title = value.title;
        this.content = value.content;
        this.firstPicture = value.firstPicture;
        this.viewCount = value.viewCount;
        this.userId = value.userId;
        this.categoryId = value.categoryId;
        this.createDate = value.createDate;
        this.updateDate = value.updateDate;
        this.description = value.description;
        this.type = value.type;
    }

    public Article(
        Long    articleId,
        Short   status,
        String  title,
        String  content,
        String  firstPicture,
        Integer viewCount,
        Long    userId,
        Long    categoryId,
        Date    createDate,
        Date    updateDate,
        String  description,
        Short   type
    ) {
        this.articleId = articleId;
        this.status = status;
        this.title = title;
        this.content = content;
        this.firstPicture = firstPicture;
        this.viewCount = viewCount;
        this.userId = userId;
        this.categoryId = categoryId;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.description = description;
        this.type = type;
    }

    public Long getArticleId() {
        return this.articleId;
    }

    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    public Short getStatus() {
        return this.status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getFirstPicture() {
        return this.firstPicture;
    }

    public void setFirstPicture(String firstPicture) {
        this.firstPicture = firstPicture;
    }

    public Integer getViewCount() {
        return this.viewCount;
    }

    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Short getType() {
        return this.type;
    }

    public void setType(Short type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Article (");

        sb.append(articleId);
        sb.append(", ").append(status);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(firstPicture);
        sb.append(", ").append(viewCount);
        sb.append(", ").append(userId);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(description);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
