/*
 * This file is generated by jOOQ.
 */
package com.ivan.sunnyblog.base.models.tables.pojos;


import java.io.Serializable;
import java.util.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlogUser implements Serializable {

    private static final long serialVersionUID = -1453668354;

    private Long   userId;
    private String username;
    private String password;
    private String nickname;
    private String email;
    private Short  status;
    private Short  role;
    private Date   createDate;
    private Date   updateDate;
    private String avatar;

    public BlogUser() {}

    public BlogUser(BlogUser value) {
        this.userId = value.userId;
        this.username = value.username;
        this.password = value.password;
        this.nickname = value.nickname;
        this.email = value.email;
        this.status = value.status;
        this.role = value.role;
        this.createDate = value.createDate;
        this.updateDate = value.updateDate;
        this.avatar = value.avatar;
    }

    public BlogUser(
        Long   userId,
        String username,
        String password,
        String nickname,
        String email,
        Short  status,
        Short  role,
        Date   createDate,
        Date   updateDate,
        String avatar
    ) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.nickname = nickname;
        this.email = email;
        this.status = status;
        this.role = role;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.avatar = avatar;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Short getStatus() {
        return this.status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public Short getRole() {
        return this.role;
    }

    public void setRole(Short role) {
        this.role = role;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BlogUser (");

        sb.append(userId);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(nickname);
        sb.append(", ").append(email);
        sb.append(", ").append(status);
        sb.append(", ").append(role);
        sb.append(", ").append(createDate);
        sb.append(", ").append(updateDate);
        sb.append(", ").append(avatar);

        sb.append(")");
        return sb.toString();
    }
}
