/*
 * This file is generated by jOOQ.
 */
package com.ivan.sunnyblog.base.models.tables.pojos;


import java.io.Serializable;
import java.util.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comment implements Serializable {

    private static final long serialVersionUID = -536183361;

    private Long   commentId;
    private Long   articleId;
    private String nickname;
    private String email;
    private String content;
    private String avatar;
    private Short  status;
    private Long   parentCommentId;
    private String parentCommentNickname;
    private Date   createdate;

    public Comment() {}

    public Comment(Comment value) {
        this.commentId = value.commentId;
        this.articleId = value.articleId;
        this.nickname = value.nickname;
        this.email = value.email;
        this.content = value.content;
        this.avatar = value.avatar;
        this.status = value.status;
        this.parentCommentId = value.parentCommentId;
        this.parentCommentNickname = value.parentCommentNickname;
        this.createdate = value.createdate;
    }

    public Comment(
        Long   commentId,
        Long   articleId,
        String nickname,
        String email,
        String content,
        String avatar,
        Short  status,
        Long   parentCommentId,
        String parentCommentNickname,
        Date   createdate
    ) {
        this.commentId = commentId;
        this.articleId = articleId;
        this.nickname = nickname;
        this.email = email;
        this.content = content;
        this.avatar = avatar;
        this.status = status;
        this.parentCommentId = parentCommentId;
        this.parentCommentNickname = parentCommentNickname;
        this.createdate = createdate;
    }

    public Long getCommentId() {
        return this.commentId;
    }

    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    public Long getArticleId() {
        return this.articleId;
    }

    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Short getStatus() {
        return this.status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public Long getParentCommentId() {
        return this.parentCommentId;
    }

    public void setParentCommentId(Long parentCommentId) {
        this.parentCommentId = parentCommentId;
    }

    public String getParentCommentNickname() {
        return this.parentCommentNickname;
    }

    public void setParentCommentNickname(String parentCommentNickname) {
        this.parentCommentNickname = parentCommentNickname;
    }

    public Date getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Comment (");

        sb.append(commentId);
        sb.append(", ").append(articleId);
        sb.append(", ").append(nickname);
        sb.append(", ").append(email);
        sb.append(", ").append(content);
        sb.append(", ").append(avatar);
        sb.append(", ").append(status);
        sb.append(", ").append(parentCommentId);
        sb.append(", ").append(parentCommentNickname);
        sb.append(", ").append(createdate);

        sb.append(")");
        return sb.toString();
    }
}
