/*
 * This file is generated by jOOQ.
 */
package com.ivan.sunnyblog.base.models.tables.records;


import com.ivan.sunnyblog.base.models.tables.Article;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleRecord extends UpdatableRecordImpl<ArticleRecord> implements Record11<Long, Short, String, String, String, Integer, Long, Long, Date, Date, String> {

    private static final long serialVersionUID = -221977525;

    /**
     * Setter for <code>public.article.article_id</code>.
     */
    public void setArticleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.article.article_id</code>.
     */
    public Long getArticleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.article.status</code>.
     */
    public void setStatus(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.article.status</code>.
     */
    public Short getStatus() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>public.article.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.article.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.article.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.article.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.article.first_picture</code>.
     */
    public void setFirstPicture(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.article.first_picture</code>.
     */
    public String getFirstPicture() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.article.view_count</code>.
     */
    public void setViewCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.article.view_count</code>.
     */
    public Integer getViewCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.article.user_id</code>.
     */
    public void setUserId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.article.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.article.category_id</code>.
     */
    public void setCategoryId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.article.category_id</code>.
     */
    public Long getCategoryId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.article.create_date</code>.
     */
    public void setCreateDate(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.article.create_date</code>.
     */
    public Date getCreateDate() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>public.article.update_date</code>.
     */
    public void setUpdateDate(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.article.update_date</code>.
     */
    public Date getUpdateDate() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>public.article.description</code>.
     */
    public void setDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.article.description</code>.
     */
    public String getDescription() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Short, String, String, String, Integer, Long, Long, Date, Date, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, Short, String, String, String, Integer, Long, Long, Date, Date, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Article.ARTICLE.ARTICLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return Article.ARTICLE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Article.ARTICLE.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Article.ARTICLE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Article.ARTICLE.FIRST_PICTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Article.ARTICLE.VIEW_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Article.ARTICLE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Article.ARTICLE.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field9() {
        return Article.ARTICLE.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field10() {
        return Article.ARTICLE.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Article.ARTICLE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getArticleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getFirstPicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getViewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component9() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component10() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getArticleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFirstPicture();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getViewCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value9() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value10() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value1(Long value) {
        setArticleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value2(Short value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value5(String value) {
        setFirstPicture(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value6(Integer value) {
        setViewCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value7(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value8(Long value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value9(Date value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value10(Date value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value11(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord values(Long value1, Short value2, String value3, String value4, String value5, Integer value6, Long value7, Long value8, Date value9, Date value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleRecord
     */
    public ArticleRecord() {
        super(Article.ARTICLE);
    }

    /**
     * Create a detached, initialised ArticleRecord
     */
    public ArticleRecord(Long articleId, Short status, String title, String content, String firstPicture, Integer viewCount, Long userId, Long categoryId, Date createDate, Date updateDate, String description) {
        super(Article.ARTICLE);

        set(0, articleId);
        set(1, status);
        set(2, title);
        set(3, content);
        set(4, firstPicture);
        set(5, viewCount);
        set(6, userId);
        set(7, categoryId);
        set(8, createDate);
        set(9, updateDate);
        set(10, description);
    }
}
