/*
 * This file is generated by jOOQ.
 */
package com.ivan.sunnyblog.base.models.tables.records;


import com.ivan.sunnyblog.base.models.tables.BlogUser;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlogUserRecord extends UpdatableRecordImpl<BlogUserRecord> implements Record10<Long, String, String, String, String, Short, Short, Date, Date, String> {

    private static final long serialVersionUID = -55745114;

    /**
     * Setter for <code>public.blog_user.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.blog_user.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.blog_user.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.blog_user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.blog_user.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.blog_user.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.blog_user.nickname</code>.
     */
    public void setNickname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.blog_user.nickname</code>.
     */
    public String getNickname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.blog_user.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.blog_user.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.blog_user.status</code>.
     */
    public void setStatus(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.blog_user.status</code>.
     */
    public Short getStatus() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.blog_user.role</code>.
     */
    public void setRole(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.blog_user.role</code>.
     */
    public Short getRole() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.blog_user.create_date</code>.
     */
    public void setCreateDate(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.blog_user.create_date</code>.
     */
    public Date getCreateDate() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>public.blog_user.update_date</code>.
     */
    public void setUpdateDate(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.blog_user.update_date</code>.
     */
    public Date getUpdateDate() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>public.blog_user.avatar</code>.
     */
    public void setAvatar(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.blog_user.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, String, String, Short, Short, Date, Date, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, String, String, String, String, Short, Short, Date, Date, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BlogUser.BLOG_USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BlogUser.BLOG_USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BlogUser.BLOG_USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BlogUser.BLOG_USER.NICKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BlogUser.BLOG_USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return BlogUser.BLOG_USER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return BlogUser.BLOG_USER.ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return BlogUser.BLOG_USER.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field9() {
        return BlogUser.BLOG_USER.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return BlogUser.BLOG_USER.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component7() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component8() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component9() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value9() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUserRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUserRecord value4(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUserRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUserRecord value6(Short value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUserRecord value7(Short value) {
        setRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUserRecord value8(Date value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUserRecord value9(Date value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUserRecord value10(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUserRecord values(Long value1, String value2, String value3, String value4, String value5, Short value6, Short value7, Date value8, Date value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BlogUserRecord
     */
    public BlogUserRecord() {
        super(BlogUser.BLOG_USER);
    }

    /**
     * Create a detached, initialised BlogUserRecord
     */
    public BlogUserRecord(Long userId, String username, String password, String nickname, String email, Short status, Short role, Date createDate, Date updateDate, String avatar) {
        super(BlogUser.BLOG_USER);

        set(0, userId);
        set(1, username);
        set(2, password);
        set(3, nickname);
        set(4, email);
        set(5, status);
        set(6, role);
        set(7, createDate);
        set(8, updateDate);
        set(9, avatar);
    }
}
