/*
 * This file is generated by jOOQ.
 */
package com.ivan.sunnyblog.base.models.tables.daos;


import com.ivan.sunnyblog.base.models.tables.Article;
import com.ivan.sunnyblog.base.models.tables.records.ArticleRecord;

import java.util.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleDao extends DAOImpl<ArticleRecord, com.ivan.sunnyblog.base.models.tables.pojos.Article, Long> {

    /**
     * Create a new ArticleDao without any configuration
     */
    public ArticleDao() {
        super(Article.ARTICLE, com.ivan.sunnyblog.base.models.tables.pojos.Article.class);
    }

    /**
     * Create a new ArticleDao with an attached configuration
     */
    public ArticleDao(Configuration configuration) {
        super(Article.ARTICLE, com.ivan.sunnyblog.base.models.tables.pojos.Article.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.ivan.sunnyblog.base.models.tables.pojos.Article object) {
        return object.getArticleId();
    }

    /**
     * Fetch records that have <code>article_id IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Article> fetchByArticleId(Long... values) {
        return fetch(Article.ARTICLE.ARTICLE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>article_id = value</code>
     */
    public com.ivan.sunnyblog.base.models.tables.pojos.Article fetchOneByArticleId(Long value) {
        return fetchOne(Article.ARTICLE.ARTICLE_ID, value);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Article> fetchByStatus(Short... values) {
        return fetch(Article.ARTICLE.STATUS, values);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Article> fetchByTitle(String... values) {
        return fetch(Article.ARTICLE.TITLE, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Article> fetchByContent(String... values) {
        return fetch(Article.ARTICLE.CONTENT, values);
    }

    /**
     * Fetch records that have <code>first_picture IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Article> fetchByFirstPicture(String... values) {
        return fetch(Article.ARTICLE.FIRST_PICTURE, values);
    }

    /**
     * Fetch records that have <code>view_count IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Article> fetchByViewCount(Integer... values) {
        return fetch(Article.ARTICLE.VIEW_COUNT, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Article> fetchByUserId(Long... values) {
        return fetch(Article.ARTICLE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>category_id IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Article> fetchByCategoryId(Long... values) {
        return fetch(Article.ARTICLE.CATEGORY_ID, values);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Article> fetchByCreateDate(Date... values) {
        return fetch(Article.ARTICLE.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>update_date IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Article> fetchByUpdateDate(Date... values) {
        return fetch(Article.ARTICLE.UPDATE_DATE, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Article> fetchByDescription(String... values) {
        return fetch(Article.ARTICLE.DESCRIPTION, values);
    }
}
