/*
 * This file is generated by jOOQ.
 */
package com.ivan.sunnyblog.base.models.tables.daos;


import com.ivan.sunnyblog.base.models.tables.Category;
import com.ivan.sunnyblog.base.models.tables.records.CategoryRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryDao extends DAOImpl<CategoryRecord, com.ivan.sunnyblog.base.models.tables.pojos.Category, Long> {

    /**
     * Create a new CategoryDao without any configuration
     */
    public CategoryDao() {
        super(Category.CATEGORY, com.ivan.sunnyblog.base.models.tables.pojos.Category.class);
    }

    /**
     * Create a new CategoryDao with an attached configuration
     */
    public CategoryDao(Configuration configuration) {
        super(Category.CATEGORY, com.ivan.sunnyblog.base.models.tables.pojos.Category.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.ivan.sunnyblog.base.models.tables.pojos.Category object) {
        return object.getCategoryId();
    }

    /**
     * Fetch records that have <code>category_id IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Category> fetchByCategoryId(Long... values) {
        return fetch(Category.CATEGORY.CATEGORY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>category_id = value</code>
     */
    public com.ivan.sunnyblog.base.models.tables.pojos.Category fetchOneByCategoryId(Long value) {
        return fetchOne(Category.CATEGORY.CATEGORY_ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.ivan.sunnyblog.base.models.tables.pojos.Category> fetchByName(String... values) {
        return fetch(Category.CATEGORY.NAME, values);
    }
}
