/*
 * This file is generated by jOOQ.
 */
package com.ivan.sunnyblog.base.models.tables;


import com.ivan.sunnyblog.base.converter.TimestampDateConverter;
import com.ivan.sunnyblog.base.models.Indexes;
import com.ivan.sunnyblog.base.models.Keys;
import com.ivan.sunnyblog.base.models.Public;
import com.ivan.sunnyblog.base.models.tables.records.BlogUserRecord;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlogUser extends TableImpl<BlogUserRecord> {

    private static final long serialVersionUID = -686600063;

    /**
     * The reference instance of <code>public.blog_user</code>
     */
    public static final BlogUser BLOG_USER = new BlogUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BlogUserRecord> getRecordType() {
        return BlogUserRecord.class;
    }

    /**
     * The column <code>public.blog_user.user_id</code>.
     */
    public final TableField<BlogUserRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('user_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.blog_user.username</code>.
     */
    public final TableField<BlogUserRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.blog_user.password</code>.
     */
    public final TableField<BlogUserRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.blog_user.nickname</code>.
     */
    public final TableField<BlogUserRecord, String> NICKNAME = createField("nickname", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.blog_user.email</code>.
     */
    public final TableField<BlogUserRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.blog_user.status</code>.
     */
    public final TableField<BlogUserRecord, Short> STATUS = createField("status", org.jooq.impl.SQLDataType.SMALLINT.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.blog_user.role</code>.
     */
    public final TableField<BlogUserRecord, Short> ROLE = createField("role", org.jooq.impl.SQLDataType.SMALLINT.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.blog_user.create_date</code>.
     */
    public final TableField<BlogUserRecord, Date> CREATE_DATE = createField("create_date", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "", new TimestampDateConverter());

    /**
     * The column <code>public.blog_user.update_date</code>.
     */
    public final TableField<BlogUserRecord, Date> UPDATE_DATE = createField("update_date", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "", new TimestampDateConverter());

    /**
     * The column <code>public.blog_user.avatar</code>.
     */
    public final TableField<BlogUserRecord, String> AVATAR = createField("avatar", org.jooq.impl.SQLDataType.VARCHAR(400), this, "");

    /**
     * Create a <code>public.blog_user</code> table reference
     */
    public BlogUser() {
        this(DSL.name("blog_user"), null);
    }

    /**
     * Create an aliased <code>public.blog_user</code> table reference
     */
    public BlogUser(String alias) {
        this(DSL.name(alias), BLOG_USER);
    }

    /**
     * Create an aliased <code>public.blog_user</code> table reference
     */
    public BlogUser(Name alias) {
        this(alias, BLOG_USER);
    }

    private BlogUser(Name alias, Table<BlogUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private BlogUser(Name alias, Table<BlogUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BlogUser(Table<O> child, ForeignKey<O, BlogUserRecord> key) {
        super(child, key, BLOG_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BLOG_USER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BlogUserRecord, Long> getIdentity() {
        return Keys.IDENTITY_BLOG_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BlogUserRecord> getPrimaryKey() {
        return Keys.BLOG_USER_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BlogUserRecord>> getKeys() {
        return Arrays.<UniqueKey<BlogUserRecord>>asList(Keys.BLOG_USER_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUser as(String alias) {
        return new BlogUser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlogUser as(Name alias) {
        return new BlogUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BlogUser rename(String name) {
        return new BlogUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BlogUser rename(Name name) {
        return new BlogUser(name, null);
    }
}
