

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sunnyblog
    username: db_user
    password: db_user_ivan
  messages:
    basename: i18n/messages
    encoding: utf-8
  redis:
    host: localhost
    port: 6379


#custom aws related config properties
aws:
#  credentials:
#    access-key: AKIATP4TEDJW2535TZHX
#    secret-key: 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
  region:
    static: ca-central-1



s3:
  bucket:
    name: res-blog-public
    path: /res-dev


