/*
 * This file is generated by jOOQ.
 */
package com.ivan.sunnyblog.base.models;


import com.ivan.sunnyblog.base.models.tables.Article;
import com.ivan.sunnyblog.base.models.tables.BlogUser;
import com.ivan.sunnyblog.base.models.tables.Category;
import com.ivan.sunnyblog.base.models.tables.Comment;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ARTICLE_PKEY = Indexes0.ARTICLE_PKEY;
    public static final Index BLOG_USER_PKEY = Indexes0.BLOG_USER_PKEY;
    public static final Index CATEGORY_PKEY = Indexes0.CATEGORY_PKEY;
    public static final Index COMMENT_PKEY = Indexes0.COMMENT_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ARTICLE_PKEY = Internal.createIndex("article_pkey", Article.ARTICLE, new OrderField[] { Article.ARTICLE.ARTICLE_ID }, true);
        public static Index BLOG_USER_PKEY = Internal.createIndex("blog_user_pkey", BlogUser.BLOG_USER, new OrderField[] { BlogUser.BLOG_USER.USER_ID }, true);
        public static Index CATEGORY_PKEY = Internal.createIndex("category_pkey", Category.CATEGORY, new OrderField[] { Category.CATEGORY.CATEGORY_ID }, true);
        public static Index COMMENT_PKEY = Internal.createIndex("comment_pkey", Comment.COMMENT, new OrderField[] { Comment.COMMENT.COMMENT_ID }, true);
    }
}
