/*
 * This file is generated by jOOQ.
 */
package com.ivan.sunnyblog.base.models;


import com.ivan.sunnyblog.base.models.tables.Article;
import com.ivan.sunnyblog.base.models.tables.BlogUser;
import com.ivan.sunnyblog.base.models.tables.Category;
import com.ivan.sunnyblog.base.models.tables.Comment;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1878344831;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.article</code>.
     */
    public final Article ARTICLE = com.ivan.sunnyblog.base.models.tables.Article.ARTICLE;

    /**
     * The table <code>public.blog_user</code>.
     */
    public final BlogUser BLOG_USER = com.ivan.sunnyblog.base.models.tables.BlogUser.BLOG_USER;

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = com.ivan.sunnyblog.base.models.tables.Category.CATEGORY;

    /**
     * The table <code>public.comment</code>.
     */
    public final Comment COMMENT = com.ivan.sunnyblog.base.models.tables.Comment.COMMENT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.BLOG_ID_SEQ,
            Sequences.CATEGORY_ID_SEQ,
            Sequences.COMMENT_ID_SEQ,
            Sequences.USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Article.ARTICLE,
            BlogUser.BLOG_USER,
            Category.CATEGORY,
            Comment.COMMENT);
    }
}
