/*
 * This file is generated by jOOQ.
 */
package com.ivan.sunnyblog.base.models;


import com.ivan.sunnyblog.base.models.tables.Article;
import com.ivan.sunnyblog.base.models.tables.BlogUser;
import com.ivan.sunnyblog.base.models.tables.Category;
import com.ivan.sunnyblog.base.models.tables.Comment;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.article</code>.
     */
    public static final Article ARTICLE = com.ivan.sunnyblog.base.models.tables.Article.ARTICLE;

    /**
     * The table <code>public.blog_user</code>.
     */
    public static final BlogUser BLOG_USER = com.ivan.sunnyblog.base.models.tables.BlogUser.BLOG_USER;

    /**
     * The table <code>public.category</code>.
     */
    public static final Category CATEGORY = com.ivan.sunnyblog.base.models.tables.Category.CATEGORY;

    /**
     * The table <code>public.comment</code>.
     */
    public static final Comment COMMENT = com.ivan.sunnyblog.base.models.tables.Comment.COMMENT;
}
